#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Docker completion
#  curl -fLo ~/.zprezto/modules/completion/external/src/_docker https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
#  compinit

. $HOME/.asdf/asdf.sh
#. $HOME/.asdf/completions/asdf.bash
. $HOME/.asdf/plugins/java/asdf-java-wrapper.zsh
. ~/.asdf/plugins/java/asdf-java-wrapper.zsh
asdf reshim java
export GOPATH=~/code/go
export PATH=${PATH}:${GOPATH}/bin
